### ISSUE TITLE
feat: find word 

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#107]
There is already a button for find in Edit -> Find ( <kbd>ctrl</kbd> + <kbd>f</kbd> ) in text editor mode, but its not working. Words that matches the find string from user should highlight on textarea.

### Solution I prefer :- 
Use the npm module called [**highlight-within-textarea**](https://www.npmjs.com/package/highlight-within-textarea). To use this module we also need to install [**jquery**](https://www.npmjs.com/package/jquery). **After installing both packages you need to done these task :-**
- [ ] Popup a small input field when user clicks on Edit -> Find ( or the shortcut <kbd>ctrl</kbd> + <kbd>f</kbd> ). Highlight the words from small input field. And should update the highlight words in textarea when the small input (find input) changes.
- [ ] Replace vanilla js using jquery.
```diff
- document.getElementById("some-id") // code like this
+ $("#some-id") // replace by using jquery
```

Helpful resources :- 
- https://www.npmjs.com/package/jquery
- https://www.npmjs.com/package/highlight-within-textarea
- https://github.com/lonekorean/highlight-within-textarea
- http://lonekorean.github.io/highlight-within-textarea
- https://stackoverflow.com/questions/32389568/search-for-a-string-from-a-textbox-in-a-textarea
- https://stackoverflow.com/questions/63793518/how-to-select-a-word-or-a-phrase-in-a-text-area-in-javascript

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this

**Comment by Emeka-Ugbanu-hub** [comment]
can you just explain what you want to do? I don't quite understand.

**Comment by Muhammed-Rahif** [comment]
@Emeka-Ugbanu-hub any help?

**Comment by Emeka-Ugbanu-hub** [comment]
should I use react-highlight-within-textarea

**Comment by Muhammed-Rahif** [comment]
Hi @Emeka-Ugbanu-hub,

I'm writing to let you know that due to unforeseen circumstances, this project has been inactive for the past few months. We apologize for any inconvenience this may have caused.

We've recently switched the technology stack of this project from ReactJS to NextJS. As a result, the issues related to the old stack are no longer applicable.

#### We've deployed the new version of the app to production, and you can access it at this link: **[https://notepad-dusky.vercel.app/](https://notepad-dusky.vercel.app/)**

I would like to take this opportunity to encourage you to actively contribute to the project. If you have any ideas, feature requests, or bug reports, please don't hesitate to create a new issue or submit a pull request on our [GitHub repository](https://github.com/Muhammed-Rahif/Notepad).

Therefore, I'm closing this issue. If you believe that the issue is still relevant to the current version of the project, please feel free to create a new issue and provide details on how to reproduce the problem.

Thank you, @Emeka-Ugbanu-hub, for your understanding and for your interest in this project! Let's work together to bring it back to life.

Best regards,  
Muhammed Rahif
