### ISSUE TITLE
fix: change production url to 'notepad.rahif.me'

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#113]
**Describe the bug :-**
Recently I changed the production URL from 'https://rahif.me/Notepad' to 'https://notepad.rahif.me'. So every line that contains 'https://rahif.me/Notepad' should be overwritten by 'https://notepad.rahif.me'.

**Additional context :-**
To find where 'https://rahif.me/Notepad' link is used:- 
**https://github.com/Muhammed-Rahif/Notepad/search?q=rahif.me%2FNotepad**

**Example :-**
```diff
- https://rahif.me/Notepad
+ https://notepad.rahif.me
```

**Comment by divyakelaskar** [comment]
I would like to work on this.

**Comment by Kannav02** [comment]
I would like to work on this issue

**Comment by Muhammed-Rahif** [comment]
@Kannav02 already assigned!

**Comment by Muhammed-Rahif** [comment]
@divyakelaskar are you working on it? Need to be fixed as soon as possible, because the production URL must be up to date everywhere in our project! Otherwise, it will occur 404 error.

**Comment by divyakelaskar** [comment]
okay, started working on it 👍
