### ISSUE TITLE
feat: save the textarea contents to 'localStorage' instantly each time the textarea content changes

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#54]
- Save the textarea contents instantly each time it changes, so if the user reloads the page the content will be there.

**Comment by anandsimmy** [comment]
Hi Rahif

Shall I take this up? I hope what you meant is, saving the data to localStorage and populating the textarea (if data is present in localStorage) whenever the user refreshes the page?

**Comment by Muhammed-Rahif** [comment]
Yes, that's what I meant.

**Comment by anandsimmy** [comment]
@Muhammed-Rahif raised pr for this issue https://github.com/Muhammed-Rahif/Notepad/pull/81. Please take a look
