### ISSUE TITLE
feat: implement full screen (maximize)

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#60]
- There is button for maximizing the window, so when user clicks on that the browser window will be setting to full screen.
- This can implement by using [react-full-screen](https://www.npmjs.com/package/react-full-screen) or [screenfull](https://www.npmjs.com/package/screenfull) (or maybe using vanilla js)

**Comment by khushbooag4** [comment]
Can I work ont this issue

**Comment by Muhammed-Rahif** [comment]
Yeah, all you need to do is toggle full screen whenever the maximize button (top right corner) clicks.

**Comment by khushbooag4** [comment]
oK

**Comment by khushbooag4** [comment]
I have created a pull requet. Kindly review it
