### ISSUE TITLE
feat: customizing font

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#62]
Like in the windows notepad, we want to customize the font settings such as font size, font family

**Comment by anandsimmy** [comment]
@Muhammed-Rahif, Shall I take this up?

**Comment by Muhammed-Rahif** [comment]
Yeah, you may already know how this feature look like, if you used notepad on windows.

A photo from internet :-
![notepad-font](https://user-images.githubusercontent.com/73386156/148670691-b0f1ec97-89b4-4ce3-b507-01811c07bb32.jpg)

**Comment by Muhammed-Rahif** [comment]
@anandsimmy but before that we need to merge #80, can you please clone that branch into your local, and review it.

**Comment by anandsimmy** [comment]
Sure. But I don't know typescript much and I even joined this project to study typescript. So if that's okay for you I could review it

**Comment by khushbooag4** [comment]
@Muhammed-Rahif  Can I work ont his issue ??

**Comment by Muhammed-Rahif** [comment]
You may already know how this feature look like, if you used notepad on windows. We need exactly that feature which allows user to customize font family, font size (with preview of how the font change will look like).

- There is already a component called `AlertBox`, it's a popup alert box. It's title and body is changeable. Please use it for this feature.
- For font families, we select some of the fonts. And use thier cdn on css file. 

More details on following comments...

**Comment by Muhammed-Rahif** [comment]
### Convert that `AlertBox` component something like this :-
![Drawing](https://user-images.githubusercontent.com/73386156/148691802-0ab7c0be-404a-44f0-89cc-cb5bf628b4b4.png)

Note :- 
- You need to save the font style changes to localStorage, and load that font styles from localStorage each time user enters to the website.

**Comment by Muhammed-Rahif** [comment]
### Example code snippets for resolving this issue :-
 
The `index.scss` file will be something like this :-
```css
/* Code that already in there
*/

@import url("some selected font url");
@import url("another selected font url");
@import url("another selected font url");
@import url("another selected font url");

body {
    font-family: 'user selected font', sans-serif;
}
```

To customize the `AlertBox` :- 
```js
import React, { useContext, useState } from "react";
import { AlertBoxContext } from "../../../contexts/Context";

function ExampleApp(){
  const { setAlertBox } = useContext(AlertBoxContext);

  const handleFontClick = () => {
          setAlertBox({
              title: "Font", // title here
              body: <h1>Alert Box body<h1/>, // alert box body here
              buttons: [
                {
                  text: "Cancel",
                  onClick: () => {
                    setAlertBox(null); // for closing the alert box
                  },
                },
                {
                  text: "Ok",
                  onClick: () => {
                    // here you need to save the font style changes to localStorage
                    setAlertBox(null); // for closing the alert box
                  },
               },
           ],
      });
  }

   return (
         <button className="menu-btn btn" onClick={handleFontClick}>
             Font
         </button>
     );
}
```

**Comment by Muhammed-Rahif** [comment]
@anandsimmy @khushbooag4 who can take all of this.. If it's seems hard or need help, please tell here.

**Comment by anandsimmy** [comment]
@khushbooag4 you can take this up

**Comment by khushbooag4** [comment]
It seems quite hard. I want to try !!

**Comment by anandsimmy** [comment]
Sure. let me or @Muhammed-Rahif know if you are facing any issues

**Comment by khushbooag4** [comment]
Sure. @Muhammed-Rahif  @anandsimmy

**Comment by Muhammed-Rahif** [comment]
@khushbooag4 may I need to take this up? I have an idea how to implement this feature. Are you already started working on this or can't do yourself? Let me work on this!

**Comment by khushbooag4** [comment]
Ok @Muhammed-Rahif  . I haven't started implementing. You can go ahead. If you can't. I want to take it up
