### ISSUE TITLE
feat: Add Color Palette 

### ISSUE THREAD

**Issue by khushbooag4** [Muhammed-Rahif/Notepad#79]
Nowdays we are using drawing notebook often for online classes. So we add an options for color palette which can make it both notepad as well as a drawing notebook.

**Comment by Muhammed-Rahif** [comment]
Can you tell more about this feature.

Are you mean a toggling between drawing mode and text editor mode? When in drawing mode user can only draw, when in text editor mode user can only edit text.

**Comment by khushbooag4** [comment]
Yes we can create a separate component for a canvas drawing mode and add a toggle between the text editor and drawing mode

**Comment by Muhammed-Rahif** [comment]
Cool, This will be one of the best if we can implement this one.

**Comment by Muhammed-Rahif** [comment]
#### I am working on this :-
![Screenshot from 2022-01-07 13-36-41](https://user-images.githubusercontent.com/73386156/148512661-a79d9468-2323-4b2d-bbb2-f375c2d4f223.png)

**Comment by Muhammed-Rahif** [comment]
@all-contributors please add @khushbooag4 for ideas
