### ISSUE TITLE
test: add tests

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#84]
### Add tests for :- 
- [x] drawpad features
- [x] dark mode and light mode
- [x] shortcuts working properly
- [x] helper file functions

**Comment by Aswin40** [comment]
Hi @Muhammed-Rahif 

Can I pick up this issue?

**Comment by Muhammed-Rahif** [comment]
@Aswin40 yeah, sure! It will be greatly appreciated if you can add valid tests! Writing test cases is boring to me :smiling_face_with_tear:.

**Comment by Aswin40** [comment]
@Muhammed-Rahif 

Is it okay to break this into four different pull requests (with same label) one for each mentioned section of testing in the description? 

1.drawpad features
2. dark mode and light mode
3. shorcuts working properly.
4. helper file functions.

**Comment by Muhammed-Rahif** [comment]
@Aswin40 okay, fine! Do it in your comfortable way.

**Comment by Muhammed-Rahif** [comment]
Resolved #128
