### ISSUE TITLE
feat: register service worker

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#85]
The project made from a PWA template, but the service worker didn't registered yet. If service worker registered, users can install the app (chrome browsers). Other browsers cache the resources, and that will load our website faster. 

**You don't need to add so more code, because there is already the code added by the template. All you need to do is remove two letters from `src/index.tsx`.**

#### The line :-
https://github.com/Muhammed-Rahif/Notepad/blob/fadaff2d6d56d1d4541ec950efbc76ab7c6e4cf3/src/index.tsx#L17

#### To Do :-
```diff
- serviceWorkerRegistration.unregister();
+ serviceWorkerRegistration.register();
```

**Comment by Abhi-paul16** [comment]
I want to work on this issue can you assign me.
