### ISSUE TITLE
fix: body background color is static, not changing on light mode

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notepad#92]
**The line to change :-**
https://github.com/Muhammed-Rahif/Notepad/blob/8883b8652a5d0796033998005f80c482bdd99f23/src/index.scss#L19

**To Reproduce :-**

1. Switch to dark mode
2. Maximize (fullscreen) the browser window
3. See black (#272727) color at the bottom of textarea 

**Expected behavior :-**
Body background should be the same of background color of textarea

**Screenshots :-**
![Screenshot from 2022-01-09 12-32-50](https://user-images.githubusercontent.com/73386156/148672840-f214eba2-fff1-4153-be52-9c4f3e62faa7.png)

**Desktop :-**

- OS: Ubuntu 20.04
- Browser: Firefox 
- Version: 95.0.1

**The solution :-**
Changing this line https://github.com/Muhammed-Rahif/Notepad/blob/8883b8652a5d0796033998005f80c482bdd99f23/src/index.scss#L19 into this may fix this issue :- 
```diff
- background-color: #272727;
+ background-color: var(--bg-color);
```

**Comment by Muhammed-Rahif** [comment]
### Tasks :-
- [ ] Change `background-color` to :- 
```diff
- background-color: #272727;
+ background-color: var(--bg-color);
```

**Comment by GrumpyMonk26** [comment]
can i be assigned to this please

**Comment by RishiKumarRay** [comment]
Hi, Sorry to say i was working on this and i Have already done the changes #99 and generated the pull request , sorry forgot to comment this

**Comment by Muhammed-Rahif** [comment]
@GrumpyMonk26 always have an eye on issues, `good-first-issue` will be created at any time.
